### ISSUE TITLE
Pass List to Task

### ISSUE THREAD

**Issue by ethnt** [ethnt/vermonster#16]
I'm trying to figure out how to pass the current list to the `Task` class. So far, no luck.

The problem is that for `Tasks::Task#update` and `Tasks::Task#create` (among others), you need the `List` ID, which currently isn' being passed to it.

**Comment by johnathancroom** [comment]
`Task` has `list_id` in the returned JSON.

Sent from my iPhone

On Jul 21, 2012, at 6:37 PM, Ethan Turkeltaub <reply 
+i- 
5757571- 
3b0d21cd2324fa83c6bdc3dc7f6ae31d54a0299d-1175259@reply.github.com>  
wrote:

**Comment by ethnt** [comment]
That solves the problem with `Tasks::Task#update`, but not `Tasks::Task#create`. Thanks for the info, though.

**Comment by johnathancroom** [comment]
``` ruby
foobar = cheddar.lists.find(42) # Returns List object
foobar.tasks.create(:text => "Be awesome!")
```

`foobar.tasks` returns an Array of Task objects. If you want to keep the current syntax, you could create a new class for that array that inherits from `Array` and give it a `#create` method. In the `#create` method, it would simply look at the `list_id` for the first `Task` in the array (they should all be the same list), and use that to create a new task. 

Example (untested):

``` ruby
class List < Hash
  def tasks
    Vermonster::Tasks::Task.from_list(self["id"])
  end
end

class Task < Hash
  class << self
    def from_list(id)
      tasks_raw = Vermonster::Client.connection.get("lists/#{id}/tasks").body
      tasks = TasksArray.new
      tasks_raw.each do |task|
        tasks.push(Task.new(task))
      end

      tasks
    end
  end
end

class TasksArray < Array
  def create
    list_id = self.first["list_id"]
    #Vermonster connection -> post /lists/#{list_id}/tasks...
  end
end
```

**Comment by ethnt** [comment]
That assumes that there are already tasks within the list. I've made a workaround by making you call `cheddar.tasks.create(24200, :text => "Foobar")` to create a list (the list ID is a parameter).

**Comment by ethnt** [comment]
I'm closing this for now.
